name: Deploy

on:
  pull_request: {}
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    uses: Flaminel/umbrella-workflows-test/.github/workflows/chart.install.yml@main
    with:
      githubContext: ${{ toJSON(github) }}
    secrets:
      PAT: ${{ secrets.PAT }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      SECRETS_TOKEN: ${{ secrets.SECRETS_TOKEN }}